config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :registers
  resources :payments
  resources :meetings
  resources :bugs
  resources :students
  resources :programs
  resources :faculties
  devise_for :users
  root 'home#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)  
    user ||= User.new
    if user.admin?
        can :manage, :all
    else
        can :read, Student
        can :read, Faculty
        can :read, Program
        can :read, Payment
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bug.rb
class Bug < ApplicationRecord
	belongs_to :user

	validates :message, presence:true
end

app/models/faculty.rb
class Faculty < ApplicationRecord
	belongs_to :user
	validates :name, presence:true
	validates :description, presence:true
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :student
  belongs_to :user

  validates :description, presence:true
  validates :time_and_date, presence:true
  validates :matric_id, presence:true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :student
  belongs_to :user

  validates :amount, presence:true
  validates :description, presence:true
  validates :matric_id, presence:true
end

app/models/program.rb
class Program < ApplicationRecord
	belongs_to :user
	validates :name, presence:true
	validates :description, presence:true
end

app/models/register.rb
class Register < ApplicationRecord
  belongs_to :student
  belongs_to :user

  validates :semester, presence:true
  validates :description, presence:true
  validates :matric_id, presence:true
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :faculty
  belongs_to :program
  belongs_to :user

  	validates :matric_id, presence:true
    validates :name, presence:true
    validates :student_status, presence:true
    validates :study_level, presence:true
    validates :current_semester, presence:true
    validates :student_type, presence:true
    validates :college, presence:true
    validates :ic_number, presence:true
    validates :passport_number, presence:true
  	validates :permanent_address, presence:true
  	validates :current_address, presence:true
    validates :country, presence:true
    validates :gender, presence:true
  	validates :date_of_birth, presence:true
    validates :mobile_number, presence:true
    validates :blood_type, presence:true
    validates :race, presence:true
    validates :religion, presence:true
    validates :marital_status, presence:true
    validates :bank, presence:true
    validates :bank_account, presence:true
    validates :sponsor, presence:true
    validates :siswa_email, presence:true
    validates :personal_email, presence:true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :faculties
  has_many :programs
  has_many :students
  has_many :bugs
  has_many :meetings
  has_many :payments
  has_many :registers
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :set_bug, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @bugs = Bug.all
  end

  def show
  end

  def new
    @bug = current_user.bugs.build
  end

  def edit
  end

  def create
    @bug = current_user.bugs.build(bug_params)

    respond_to do |format|
      if @bug.save
        format.html { redirect_to @bug, notice: 'Bug was successfully created.' }
        format.json { render :show, status: :created, location: @bug }
      else
        format.html { render :new }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @bug.update(bug_params)
        format.html { redirect_to @bug, notice: 'Bug was successfully updated.' }
        format.json { render :show, status: :ok, location: @bug }
      else
        format.html { render :edit }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @bug.destroy
    respond_to do |format|
      format.html { redirect_to bugs_url, notice: 'Bug was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_bug
      @bug = Bug.find(params[:id])
    end
    
    def bug_params
      params.require(:bug).permit(:user_id, :message)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @meetings = Meeting.all
  end

  def show
  end

  def new
    @meeting = current_user.meetings.build
  end

  def edit
  end

  def create
    @meeting = current_user.meetings.build(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    def meeting_params
      params.require(:meeting).permit(:user_id, :time_and_date, :description, :matric_id, :student_id)
    end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  load_and_authorize_resource
  before_action :set_program, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @programs = Program.where(["name LIKE ?","%#{params[:search]}%"])
  end

  def show
  end

  def new
    @program = current_user.programs.build
  end

  def edit
  end

  def create
    @program = current_user.programs.build(program_params)

    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render :show, status: :created, location: @program }
      else
        format.html { render :new }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { render :show, status: :ok, location: @program }
      else
        format.html { render :edit }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to programs_url, notice: 'Program was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_program
      @program = Program.find(params[:id])
    end

    def program_params
      params.require(:program).permit(:user_id, :name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/programs/_form.html.erb
<%= simple_form_for(@program) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :user_id,:as => :hidden %>
    <%= f.input :name %>
    <%= f.input :description,input_html:{rows:8}%>
  </div>

  <div class="form-actions">
    <%= f.button :submit,:class=>"btn btn-danger btn-block"%>
  </div>
<% end %>

app/views/programs/edit.html.erb
<% provide(:program, "active") %>
<div class="container">
	<div class="program-edit">
	<div class="row">
		<div class="col-sm-12 col-md-12 col-lg-12">
			<h6 class="text-center">Edit Program</h6>
			<%= render 'form', program: @program %>
		</div>
	</div>
</div>
</div>

app/views/programs/index.html.erb
<% provide(:program, "active") %>
<div class="container">
  <div class="program-index">
    <div class="row justify-content-center">
      <div class="col-sm-12 col-md-12 col-lg-12">
        <div class="card">
          <div class="card-body">
            <div class="search">
              <form class="form-inline my-2 my-lg-0">
                <%= form_tag programs_path, :method => 'get' do %>
                  <%= text_field_tag :search,params[:search],:class=>"form-control",:placeholder => "Search by Program Name"%>
                  <div class="my-btn" style="margin-top: 4px">
                    <%= submit_tag "Search",:class=>"btn btn-danger btn-block "%>
                  </div>
                <% end %>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
    <% @programs.each do |program| %>
      <div class="col-sm-12 col-md-12 col-lg-12">
        <div class="card">
          <div class="card-body">
            <h6 class="card-text"><%= link_to program.name %></h6>
            <div class="button-group">
              <%= link_to "Show",program,:class=>"btn btn-secondary btn-sm"%>
              <% if can? :update, @program %>
                <%= link_to "Edit",edit_program_path(program),:class=>"btn btn-secondary btn-sm"%>
              <% end %>
              <% if can? :destroy, @program %>
                <%= link_to "Delete",program_path(program),method: :delete,data:{confirm:'Are you sure?'},:class=>"btn btn-secondary btn-sm"%>
              <% end %>
            </div>
            <div class="small">Added at <%= program.created_at.strftime("%B,%d,%Y")%></div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <% if can? :create, @program %>
    <div class="row" style="padding: 5px 0px">
      <div class="col-sm-12 col-md-12 col-lg-12">
        <%= link_to 'Add New Program', new_program_path,:class=>"btn btn-danger btn-block" %>
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/programs/new.html.erb
<% provide(:program, "active") %>
<div class="container">
	<div class="program-new">
	<div class="row">
		<div class="col-sm-12 col-md-12 col-lg-12">
			<h5 class="text-center">Add New Program</h5>
			<%= render 'form', program: @program %>
		</div>
	</div>
</div>
</div>

app/views/programs/show.html.erb
<% provide(:program, "active") %>
<div class="container">
	<div class="faculty-show">
	<div class="row">
		<div class="col-sm-12 col-md-12 col-lg-12">
			<div class="card">
				<div class="card-body">
					<h6 class="card-text text-center"><%= @program.name %></h6>
					<hr class="my-4">
					<p class="card-text text-justify"><%= @program.description %></p>
					<small>Added <%= time_ago_in_words(@program.created_at)%> ago</small>
				</div>
			</div>
		</div>
	</div>
	<% if can? :update, @program%>
		<div class="row" style="padding: 5px 0px">
			<div class="col-sm-12 col-md-12 col-lg-12">
				<%= link_to 'Edit Program', edit_program_path(@program),:class=>"btn btn-danger btn-block"%>
			</div>
		</div>
	<% end %>
</div>
</div>