config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :registers
  resources :payments
  resources :meetings
  resources :bugs
  resources :students
  resources :programs
  resources :faculties
  devise_for :users
  root 'home#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)  
    user ||= User.new
    if user.admin?
        can :manage, :all
    else
        can :read, Student
        can :read, Faculty
        can :read, Program
        can :read, Payment
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bug.rb
class Bug < ApplicationRecord
	belongs_to :user

	validates :message, presence:true
end

app/models/faculty.rb
class Faculty < ApplicationRecord
	belongs_to :user
	validates :name, presence:true
	validates :description, presence:true
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :student
  belongs_to :user

  validates :description, presence:true
  validates :time_and_date, presence:true
  validates :matric_id, presence:true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :student
  belongs_to :user

  validates :amount, presence:true
  validates :description, presence:true
  validates :matric_id, presence:true
end

app/models/program.rb
class Program < ApplicationRecord
	belongs_to :user
	validates :name, presence:true
	validates :description, presence:true
end

app/models/register.rb
class Register < ApplicationRecord
  belongs_to :student
  belongs_to :user

  validates :semester, presence:true
  validates :description, presence:true
  validates :matric_id, presence:true
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :faculty
  belongs_to :program
  belongs_to :user

  	validates :matric_id, presence:true
    validates :name, presence:true
    validates :student_status, presence:true
    validates :study_level, presence:true
    validates :current_semester, presence:true
    validates :student_type, presence:true
    validates :college, presence:true
    validates :ic_number, presence:true
    validates :passport_number, presence:true
  	validates :permanent_address, presence:true
  	validates :current_address, presence:true
    validates :country, presence:true
    validates :gender, presence:true
  	validates :date_of_birth, presence:true
    validates :mobile_number, presence:true
    validates :blood_type, presence:true
    validates :race, presence:true
    validates :religion, presence:true
    validates :marital_status, presence:true
    validates :bank, presence:true
    validates :bank_account, presence:true
    validates :sponsor, presence:true
    validates :siswa_email, presence:true
    validates :personal_email, presence:true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :faculties
  has_many :programs
  has_many :students
  has_many :bugs
  has_many :meetings
  has_many :payments
  has_many :registers
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :set_bug, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @bugs = Bug.all
  end

  def show
  end

  def new
    @bug = current_user.bugs.build
  end

  def edit
  end

  def create
    @bug = current_user.bugs.build(bug_params)

    respond_to do |format|
      if @bug.save
        format.html { redirect_to @bug, notice: 'Bug was successfully created.' }
        format.json { render :show, status: :created, location: @bug }
      else
        format.html { render :new }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @bug.update(bug_params)
        format.html { redirect_to @bug, notice: 'Bug was successfully updated.' }
        format.json { render :show, status: :ok, location: @bug }
      else
        format.html { render :edit }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @bug.destroy
    respond_to do |format|
      format.html { redirect_to bugs_url, notice: 'Bug was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_bug
      @bug = Bug.find(params[:id])
    end
    
    def bug_params
      params.require(:bug).permit(:user_id, :message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyAMS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
  </head>
  <body>
      <%= render 'shared/navbar'%>
      <br>
      <%= render 'shared/alert'%>
      <%= yield %>
      <script>
        particlesJS('particles-js',
          {
            "particles": {
              "number": {
                "value": 80,
                "density": {
                  "enable": true,
                  "value_area": 800
                }
              },
              "color": {
                "value": "#ffffff"
              },
              "shape": {
                "type": "circle",
                "stroke": {
                  "width": 0,
                  "color": "#000000"
                },
                "polygon": {
                  "nb_sides": 5
                },
                "image": {
                  "src": "img/github.svg",
                  "width": 100,
                  "height": 100
                }
              },
              "opacity": {
                "value": 0.5,
                "random": false,
                "anim": {
                  "enable": false,
                  "speed": 1,
                  "opacity_min": 0.1,
                  "sync": false
                }
              },
              "size": {
                "value": 5,
                "random": true,
                "anim": {
                  "enable": false,
                  "speed": 40,
                  "size_min": 0.1,
                  "sync": false
                }
              },
              "line_linked": {
                "enable": true,
                "distance": 150,
                "color": "#ffffff",
                "opacity": 0.4,
                "width": 1
              },
              "move": {
                "enable": true,
                "speed": 6,
                "direction": "none",
                "random": false,
                "straight": false,
                "out_mode": "out",
                "attract": {
                  "enable": false,
                  "rotateX": 600,
                  "rotateY": 1200
                }
              }
            },
            "interactivity": {
              "detect_on": "canvas",
              "events": {
                "onhover": {
                  "enable": true,
                  "mode": "repulse"
                },
                "onclick": {
                  "enable": true,
                  "mode": "push"
                },
                "resize": true
              },
              "modes": {
                "grab": {
                  "distance": 400,
                  "line_linked": {
                    "opacity": 1
                  }
                },
                "bubble": {
                  "distance": 400,
                  "size": 40,
                  "duration": 2,
                  "opacity": 8,
                  "speed": 3
                },
                "repulse": {
                  "distance": 200
                },
                "push": {
                  "particles_nb": 4
                },
                "remove": {
                  "particles_nb": 2
                }
              }
            },
            "retina_detect": true,
            "config_demo": {
              "hide_card": false,
              "background_color": "#b61924",
              "background_image": "",
              "background_position": "50% 50%",
              "background_repeat": "no-repeat",
              "background_size": "cover"
            }
          }
        );
      </script>
  </body>
</html>

app/views/shared/_alert.html.erb
<div class="container">
	<div class="row justify-content-center">
	<div class="col-sm-12 col-md-12 col-lg-12">
		<br>
<% if flash[:notice] %>
	<div class="alert alert-success">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<%= flash[:notice] %>
	</div>
<% elsif flash[:error] %>
	<div class="alert alert-danger">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<%= flash[:error] %>
	</div>
<% elsif flash[:alert] %>
	<div class="alert alert-warning">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<%= flash[:alert] %>
	</div>
<% end %>
	</div>
</div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <%= link_to "муαмѕ",root_path,:class=>"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item <%= yield(:advisee_list)%>">
            <%= link_to "Advisee List",students_path,:class=>"nav-link"%>
          </li>
          <% if current_user.admin? %>
          <li class="nav-item <%= yield(:faculty)%>">
            <%= link_to "Faculties",faculties_path,:class=>"nav-link"%>
          </li>
          <li class="nav-item <%= yield(:program)%>">
            <%= link_to "Programs",programs_path,:class=>"nav-link"%>
          </li>
          <% end %>
          <li class="nav-item <%= yield(:payment)%>">
            <%= link_to "Payments",payments_path,:class=>"nav-link"%>
          </li>
          <li class="nav-item <%= yield(:register)%>">
            <%= link_to "Registrations",registers_path,:class=>"nav-link"%>
          </li>
          <li class="nav-item <%= yield(:meeting)%>">
            <%= link_to "Meeting",meetings_path,:class=>"nav-link"%>
          </li>
          <li class="nav-item <%= yield(:bug)%>">
            <%= link_to "Report Bug",bugs_path,:class=>"nav-link"%>
          </li>
          <li class="nav-item <%= yield(:sign_out)%>">
            <%= link_to "Sign-out",destroy_user_session_path,method: :delete,:class=>"nav-link"%>
          </li>
          <li class="nav-item <%= yield(:sign_out)%>">
            <div class="nav-link"><%= current_user.email %></div>
          </li>
        <% else %>
          <li class="nav-item <%= yield(:sign_in)%>">
            <%= link_to "Sign-in",new_user_session_path,:class=>"nav-link"%>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>