config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :registers
  resources :payments
  resources :meetings
  resources :bugs
  resources :students
  resources :programs
  resources :faculties
  devise_for :users
  root 'home#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)  
    user ||= User.new
    if user.admin?
        can :manage, :all
    else
        can :read, Student
        can :read, Faculty
        can :read, Program
        can :read, Payment
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bug.rb
class Bug < ApplicationRecord
	belongs_to :user

	validates :message, presence:true
end

app/models/faculty.rb
class Faculty < ApplicationRecord
	belongs_to :user
	validates :name, presence:true
	validates :description, presence:true
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :student
  belongs_to :user

  validates :description, presence:true
  validates :time_and_date, presence:true
  validates :matric_id, presence:true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :student
  belongs_to :user

  validates :amount, presence:true
  validates :description, presence:true
  validates :matric_id, presence:true
end

app/models/program.rb
class Program < ApplicationRecord
	belongs_to :user
	validates :name, presence:true
	validates :description, presence:true
end

app/models/register.rb
class Register < ApplicationRecord
  belongs_to :student
  belongs_to :user

  validates :semester, presence:true
  validates :description, presence:true
  validates :matric_id, presence:true
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :faculty
  belongs_to :program
  belongs_to :user

  	validates :matric_id, presence:true
    validates :name, presence:true
    validates :student_status, presence:true
    validates :study_level, presence:true
    validates :current_semester, presence:true
    validates :student_type, presence:true
    validates :college, presence:true
    validates :ic_number, presence:true
    validates :passport_number, presence:true
  	validates :permanent_address, presence:true
  	validates :current_address, presence:true
    validates :country, presence:true
    validates :gender, presence:true
  	validates :date_of_birth, presence:true
    validates :mobile_number, presence:true
    validates :blood_type, presence:true
    validates :race, presence:true
    validates :religion, presence:true
    validates :marital_status, presence:true
    validates :bank, presence:true
    validates :bank_account, presence:true
    validates :sponsor, presence:true
    validates :siswa_email, presence:true
    validates :personal_email, presence:true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :faculties
  has_many :programs
  has_many :students
  has_many :bugs
  has_many :meetings
  has_many :payments
  has_many :registers
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :set_bug, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @bugs = Bug.all
  end

  def show
  end

  def new
    @bug = current_user.bugs.build
  end

  def edit
  end

  def create
    @bug = current_user.bugs.build(bug_params)

    respond_to do |format|
      if @bug.save
        format.html { redirect_to @bug, notice: 'Bug was successfully created.' }
        format.json { render :show, status: :created, location: @bug }
      else
        format.html { render :new }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @bug.update(bug_params)
        format.html { redirect_to @bug, notice: 'Bug was successfully updated.' }
        format.json { render :show, status: :ok, location: @bug }
      else
        format.html { render :edit }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @bug.destroy
    respond_to do |format|
      format.html { redirect_to bugs_url, notice: 'Bug was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_bug
      @bug = Bug.find(params[:id])
    end
    
    def bug_params
      params.require(:bug).permit(:user_id, :message)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @meetings = Meeting.all
  end

  def show
  end

  def new
    @meeting = current_user.meetings.build
  end

  def edit
  end

  def create
    @meeting = current_user.meetings.build(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    def meeting_params
      params.require(:meeting).permit(:user_id, :time_and_date, :description, :matric_id, :student_id)
    end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  load_and_authorize_resource
  before_action :set_payment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @payments = Payment.where(["matric_id LIKE ?","%#{params[:search]}%"])
  end

  def show
  end

  def new
    @payment = current_user.payments.build
  end

  def edit
  end

  def create
    @payment = current_user.payments.build(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_payment
      @payment = Payment.find(params[:id])
    end
    
    def payment_params
      params.require(:payment).permit(:user_id, :amount, :description, :student_id,:matric_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/bugs/_form.html.erb
<%= simple_form_for(@bug) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :user_id,:as => :hidden %>
    <%= f.input :message,input_html:{rows:8}%>
  </div>

  <div class="form-actions">
    <%= f.button :submit,:class=>"btn btn-danger btn-block"%>
  </div>
<% end %>

app/views/bugs/edit.html.erb
<% provide(:bug, "active") %>
<div class="container">
	<div class="bug-edit">
	<div class="row">
		<div class="col-sm-12 col-md-12 col-lg-12">
			<h5 class="text-center">Edit Bug</h5>
			<%= render 'form', bug: @bug %>
		</div>
	</div>
</div>
</div>

app/views/bugs/index.html.erb
<% provide(:bug, "active") %>
<div class="container">
  <div class="bug-index">
    <div class="row">
    <% @bugs.each do |bug| %>
      <div class="col-sm-12 col-md-12 col-lg-12">
        <div class="card">
          <div class="card-body">
            <h6 class="card-text text-justify"><%= link_to bug.message, bug %></h6>
            <div class="button-group">
              <%= link_to "Show",bug,:class=>"btn btn-secondary btn-sm"%>
              <%= link_to "Edit",edit_bug_path(bug),:class=>"btn btn-secondary btn-sm"%>
              <%= link_to "Delete",bug_path(bug),method: :delete,data:{confirm:'Are you sure?'},:class=>"btn btn-secondary btn-sm"%>
            </div>
            <div class="small">Reported at <%= bug.created_at.strftime("%B,%d,%Y")%></div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row" style="padding: 5px 0px">
    <div class="col-sm-12 col-md-12 col-lg-12">
      <%= link_to 'Submit New Bug', new_bug_path,:class=>"btn btn-danger btn-block" %>
    </div>
  </div>
</div>
</div>

app/views/bugs/new.html.erb
<% provide(:bug, "active") %>
<div class="container">
	<div class="bug-new">
	<div class="row">
		<div class="col-sm-12 col-md-12 col-lg-12">
			<h5 class="text-center">Report New Bug</h5>
			<%= render 'form', bug: @bug %>
		</div>
	</div>
</div>
</div>

app/views/bugs/show.html.erb
<% provide(:bug, "active") %>
<div class="container">
	<div class="bug-show">
	<div class="row">
		<div class="col-sm-12 col-md-12 col-lg-12">
			<div class="card">
				<div class="card-body">
					<h6 class="card-text text-center">Reported by <%= current_user.email %></h6>
					<hr class="my-4">
					<p class="card-text"><%= @bug.message %></p>
					<small>Submitted about <%= time_ago_in_words(@bug.created_at)%> ago</small>
				</div>
			</div>
		</div>
	</div>
	<div class="row" style="padding: 5px 0px">
		<div class="col-sm-12 col-md-12 col-lg-12">
			<%= link_to 'Edit Bug', edit_bug_path(@bug),:class=>"btn btn-danger btn-block"%>
		</div>
	</div>
</div>
</div>

app/views/meetings/_form.html.erb
<%= simple_form_for(@meeting) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :user_id,:as => :hidden %>
    <%= f.association :student,prompt:"Select Student" %>
    <%= f.input :matric_id, label:"Matric ID"%>
    <%= f.input :time_and_date,label: "Time and Date"%>
    <%= f.input :description,input_html:{rows:6}%>
  </div>

  <div class="form-actions">
    <%= f.button :submit,:class=>"btn btn-danger btn-block"%>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<% provide(:meeting, "active") %>
<div class="container">
	<div class="meeting-edit">
	<div class="row">
		<div class="col-sm-12 col-md-12 col-lg-12">
			<h6 class="text-center">Edit Meeting</h6>
			<%= render 'form', meeting: @meeting %>
		</div>
	</div>
</div>
</div>

app/views/meetings/index.html.erb
<% provide(:meeting, "active") %>
<div class="container">
  <div class="meeting-index">
    <div class="row justify-content-center">
      <div class="col-sm-12 col-md-12 col-lg-12">
        <div class="card">
          <div class="card-body">
            <div class="search">
              <form class="form-inline my-2 my-lg-0">
                <%= form_tag meetings_path, :method => 'get' do %>
                  <%= text_field_tag :search,params[:search],:class=>"form-control",:placeholder => "Search by Matric ID"%>
                  <div class="my-btn" style="margin-top: 4px">
                    <%= submit_tag "Search",:class=>"btn btn-danger btn-block"%>
                  </div>
                <% end %>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
    <% @meetings.each do |meeting| %>
      <div class="col-sm-12 col-md-12 col-lg-12">
        <div class="card">
          <div class="card-body">
            <h6 class="card-text"><%= link_to meeting.student.name %> | <%= link_to meeting.student.matric_id, meeting%></h6>
            <div class="button-group">
              <%= link_to "Show",meeting,:class=>"btn btn-secondary btn-sm"%>
              <%= link_to "Edit",edit_meeting_path(meeting),:class=>"btn btn-secondary btn-sm"%>
              <%= link_to "Delete",meeting_path(meeting),method: :delete,data:{confirm:'Are you sure?'},:class=>"btn btn-secondary btn-sm"%>
            </div>
            <div class="small">Meeting at <strong><%= meeting.created_at%></strong></div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row" style="padding: 5px 0px">
    <div class="col-sm-12 col-md-12 col-lg-12">
      <%= link_to 'Add New Meeting', new_meeting_path,:class=>"btn btn-danger btn-block" %>
    </div>
  </div>
</div>
</div>

app/views/meetings/new.html.erb
<% provide(:meeting, "active") %>
<div class="container">
	<div class="meeting-new">
	<div class="row">
		<div class="col-sm-12 col-md-12 col-lg-12">
			<h5 class="text-center">Add New Meeting</h5>
			<%= render 'form', meeting: @meeting %>
		</div>
	</div>
</div>
</div>

app/views/meetings/show.html.erb
<% provide(:meeting, "active") %>
<div class="container">
  <div class="meeting-show">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
      <div class="card">
        <div class="card-body">
          <h6 class="card-text text-center"><%= @meeting.student.name %> | <%= @meeting.student.matric_id %></h6>
          <hr class="my-4">
          <p class="card-text"><%= @meeting.description %></p>
          <small>Set about <%= time_ago_in_words(@meeting.created_at)%> ago</small>
        </div>
      </div>
    </div>
  </div>
  <div class="row" style="padding: 5px 0px">
    <div class="col-sm-12 col-md-12 col-lg-12">
      <%= link_to 'Edit Meeting', edit_meeting_path(@meeting),:class=>"btn btn-danger btn-block"%>
    </div>
  </div>
</div>
</div>

app/views/payments/_form.html.erb
<%= simple_form_for(@payment) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :user_id,:as => :hidden %>
    <%= f.association :student,prompt:"Select Student"%>
    <%= f.input :matric_id,label:"Matric ID"%>
    <%= f.input :amount %>
    <%= f.input :description,input_html:{rows:6}%>
  </div>
  <div class="form-actions">
    <%= f.button :submit,:class=>"btn btn-danger btn-block"%>
  </div>
<% end %>

app/views/payments/edit.html.erb
<% provide(:payment, "active") %>
<div class="container">
	<h1>Editing Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>
</div>

app/views/payments/index.html.erb
<% provide(:payment, "active") %>
<div class="container">
  <div class="payment-index">
    <div class="row justify-content-center">
      <div class="col-sm-12 col-md-12 col-lg-12">
        <div class="card">
          <div class="card-body">
            <div class="search">
              <form class="form-inline my-2 my-lg-0">
                <%= form_tag payments_path, :method => 'get' do %>
                  <%= text_field_tag :search,params[:search],:class=>"form-control",:placeholder => "Search by Matric Id"%>
                  <div class="my-btn" style="margin-top: 4px">
                    <%= submit_tag "Search",:class=>"btn btn-danger btn-block"%>
                  </div>
                <% end %>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  <div class="row">
    <% @payments.each do |payment| %>
      <div class="col-sm-12 col-md-12 col-lg-12">
        <div class="card">
          <div class="card-body">
            <h5 class="card-text"><%= link_to payment.student.name,payment %> | <%= link_to payment.student.matric_id,payment%></h5>
            <small>Deposited <strong><%= payment.amount %> MYR</strong> at <%= payment.created_at.strftime("%B,%d,%Y")%></small>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <% if can? :create, @payment %>
    <div class="row" style="padding: 5px 0px">
      <div class="col-sm-12 col-md-12 col-lg-12">
        <%= link_to 'New Payment', new_payment_path,:class=>"btn btn-danger btn-block"%>
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/payments/new.html.erb
<% provide(:payment, "active") %>
<div class="container">
	<div class="payment-new">
	<div class="row">
		<div class="col-sm-12 col-md-12 col-lg-12">
			<h5 class="text-center">Add New Payment</h5>
			<%= render 'form', payment: @payment %>
		</div>
	</div>
</div>
</div>

app/views/payments/show.html.erb
<% provide(:payment, "active") %>
<div class="container">
  <div class="payment-show">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
      <div class="card">
        <div class="card-body">
          <h6 class="card-text text-center">Payment Deposited by <%= @payment.student.name %></h6>
          <hr class="my-4">
          <table>
            <tr>
              <td>Student Matric ID</td>
              <td style="padding-left: 10px">: <%= @payment.student.matric_id %></td>
            </tr>
            <tr>
              <td>Payment ID</td>
              <td style="padding-left: 10px">: <%="#{@payment.student.matric_id}"%>-<%= "#{@payment.id}" %></td>
            </tr>
            <tr>
              <td>Amount</td>
              <td style="padding-left: 10px">: <%= @payment.amount %> </td>
            </tr>
            <tr>
              <td>Description</td>
              <td style="padding-left: 10px">: <%= @payment.description %></td>
            </tr>
          </table>
          <div class="text-center" style="padding-top: 10px">
            <small><%= @payment.created_at.strftime("%b,%d,%Y")%></small>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row" style="padding-top: 5px">
    <div class="col-sm-12 col-md-12 col-lg-12">
      <%= link_to 'Back', payments_path,:class=>"btn btn-danger btn-block"%>
    </div>
  </div>
</div>
</div>